Require click>=8.0.0
Version 7.1.2 of click lacks decorators.FC, resulting in `ImportError:
cannot import name 'FC'` if pulp-cli is installed using pip with click
7.1.2 already installed.

[noissue]