Only set auth_provider if a no cert is provided
Otherwise (e.g. when using cert auth), pulp_glue will error out with:

    Error: Cannot use both 'auth' and 'cert'.

Fixes: 954a7bd4899e56d641949f6a5f0fd2f257c26ae0
(cherry picked from commit 2fca797e88ef059911b078011d98f00b3239a087)