Pin schema due to breakage in 0.7.6.
Example:
~ $ pip install schema
...
Successfully installed contextlib2-21.6.0 schema-0.7.6
~ $ python3
>>> import schema as s
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'schema'
>>>

[noissue]